version: '3.6'
services:
  mongo:
    container_name: test-2-mongo
    image: mongo:4.2
    command: --replSet rs --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - test-2
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  mongo-replicator:
    container_name: test-2-mongo-replicator
    build: ./api/mongo-replicator
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=rs
    networks:
      - test-2
    depends_on:
      - mongo
  redis:
    container_name: test-2-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - test-2
    ports:
      - 6379:6379
  api:
    container_name: test-2-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      target: api
      args:
        APP_ENV: development
    networks:
      - test-2
    volumes:
      - ./api/src:/app/src
    ports:
      - 3001:3001
    depends_on:
      - redis
      - mongo-replicator
  migrator:
    container_name: test-2-migrator
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      target: migrator
      args:
        APP_ENV: development
    networks:
      - test-2
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo-replicator
  scheduler:
    container_name: test-2-scheduler
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      target: scheduler
      args:
        APP_ENV: development
    networks:
      - test-2
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo-replicator
  web:
    container_name: test-2-web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      args:
        APP_ENV: development
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    networks:
      - test-2
    ports:
      - 3002:3002

networks:
  test-2:
    name: test-2-network

volumes:
  mongodb:
  mongodb-cfg:
